/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lab3.ui;

import com.mycompany.lab3.model.User;
import java.awt.Image;
import java.io.File;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author syedahmed
 */
public class UserForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserForm.class.getName());
    private String filePath = null;
    /**
     * Creates new form UserForm
     */
    public UserForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        buttonSubmit = new javax.swing.JButton();
        buttonUpload = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        textFirstName = new javax.swing.JTextField();
        spinnerAge = new javax.swing.JSpinner();
        comboBoxContinent = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        textExperience = new javax.swing.JTextArea();
        textPhoneNumber = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        textLastName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtHobbies = new javax.swing.JTextArea();
        comboBoxGender = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtemail = new javax.swing.JFormattedTextField();
        txtFilePath = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Last Name");

        jLabel3.setText("Gender");

        jLabel4.setText("Age");

        jLabel5.setText("Phone Number");

        jLabel6.setText("Continent");

        jLabel7.setText("Experience");

        buttonSubmit.setText("Submit");
        buttonSubmit.addActionListener(this::buttonSubmitActionPerformed);

        buttonUpload.setText("Upload");
        buttonUpload.addActionListener(this::buttonUploadActionPerformed);

        jLabel8.setText("Photo");

        textFirstName.addActionListener(this::textFirstNameActionPerformed);

        spinnerAge.setDoubleBuffered(true);

        comboBoxContinent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asia", "Africa", "Europe", "North America", "South America", "Antarctica", " " }));

        textExperience.setColumns(20);
        textExperience.setRows(5);
        jScrollPane3.setViewportView(textExperience);

        try {
            textPhoneNumber.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        textPhoneNumber.setToolTipText("123-123-1234");
        textPhoneNumber.addActionListener(this::textPhoneNumberActionPerformed);

        jLabel1.setText("First Name");

        jLabel9.setText("Hobbies");

        txtHobbies.setColumns(20);
        txtHobbies.setRows(5);
        jScrollPane1.setViewportView(txtHobbies);

        comboBoxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jLabel10.setText("Email");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(buttonSubmit))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxContinent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinnerAge, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(textLastName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textFirstName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtemail, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textPhoneNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtFilePath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(18, 18, 18)
                                    .addComponent(buttonUpload))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(comboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxContinent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(73, 73, 73))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addComponent(buttonUpload, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFilePath, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(buttonSubmit)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubmitActionPerformed
        // TODO add your handling code here:
        String firstName = textFirstName.getText();
        String lastName = textLastName.getText();
        String phoneNumber = textPhoneNumber.getText();
        String experience = textExperience.getText();
        String hobbies = txtHobbies.getText();
        String email = txtemail.getText();
        int age = (int) spinnerAge.getValue();
        String gender = comboBoxGender.getSelectedItem().toString();
        String continent = comboBoxContinent.getSelectedItem().toString();

        if(isNullorEmpty(firstName)){
            displayMessage("Please Enter First name","Validation Error");
            return;
        }

        if(isNullorEmpty(lastName)){
            displayMessage("Please Enter Last name","Validation Error");
            return;
        }

        if(isNullorEmpty(phoneNumber)){
            displayMessage("Please Enter Phone Number","Validation Error");
            return;
        }
        
        if (phoneNumber.replace("-","").trim().isEmpty()){
            displayMessage("Please Enter valid Phone Number","Validation Error");
            return;
        }
        

        if(isNullorEmpty(experience)){
            displayMessage("Please provide the experience","Validation Error");
            return;
        }

        if(isNullorEmpty(gender)){
            displayMessage("Please provide your Gender","Validation Error");
            return;
        }

        if(isNullorEmpty(email)){
            displayMessage("Please provide your Email","Validation Error");
            return;
        }
        Pattern EMAIL_PATTERN = Pattern.compile(
        "^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,6}$"
        );

        Matcher matcher = EMAIL_PATTERN.matcher(email);
        
        if (!matcher.matches()){
            displayMessage("Please provide valid Email","Validation Error");
            return;

        }
        if(isNullorEmpty(hobbies)){
            displayMessage("Please provide some of your hobbies","Validation Error");
            return;
        }

        if(age <= 0){
            displayMessage("Please provide valid age","Validation Error");
            return;
        }
        
        if (isNullorEmpty(filePath)){
            displayMessage("Please select Picture","Validation Error");
            return;
        }
        

        User user = new User(firstName, lastName, age, gender, phoneNumber, email,continent,experience, hobbies,filePath);
        displaySuccessMessage(user.toString(), "Success",user.getPhotoUrl());

    }//GEN-LAST:event_buttonSubmitActionPerformed

    private void textFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFirstNameActionPerformed

    private void textPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPhoneNumberActionPerformed

    }//GEN-LAST:event_textPhoneNumberActionPerformed

    private void buttonUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUploadActionPerformed
        // TODO add your handling code here:
        filePath = uploadFile();
        txtFilePath.setText(filePath);

    }//GEN-LAST:event_buttonUploadActionPerformed

    
    private String uploadFile(){
       
        // 1. Create the file chooser
        JFileChooser fileChooser = new JFileChooser();

        // 2. Define the filter for JPEG extensions (.jpg and .jpeg)
        FileNameExtensionFilter jpegFilter = new FileNameExtensionFilter("JPEG Images (*.jpg, *.jpeg)", "jpg", "jpeg");

        // 3. Apply the filter and disable the "All Files (*.*)" option
        fileChooser.setFileFilter(jpegFilter);
        fileChooser.setAcceptAllFileFilterUsed(false); // Prevents users from switching back to "All Files"
          
        // 4. Open the dialog
        int result = fileChooser.showOpenDialog(null);
        // 3. Extract and return the absolute file path
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            return selectedFile.getAbsolutePath(); // Returns the full system path as a String
        }

        // Return null or an empty string if the user closes/cancels the dialog
        return null; 
    }
    
    private void displaySuccessMessage(String message, String header,String photoUrl){
             
            ImageIcon originalIcon = new ImageIcon(photoUrl);
            
            
        // 2. Extract the Image object and resize it (e.g., 100x100 pixels)
            Image scaledImage = originalIcon.getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH);

            // 3. Create a new ImageIcon from the resized image
            ImageIcon resizedIcon = new ImageIcon(scaledImage);
        
            JOptionPane.showMessageDialog(this, message, header,
                                           JOptionPane.INFORMATION_MESSAGE,resizedIcon);
         
    
    }
    private void displayMessage(String message, String header){
         
        JOptionPane.showMessageDialog(this, message, header,
                                           JOptionPane.INFORMATION_MESSAGE);
    }
    
    private boolean isNullorEmpty(String text){
        return text == null || text.isEmpty();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSubmit;
    private javax.swing.JButton buttonUpload;
    private javax.swing.JComboBox<String> comboBoxContinent;
    private javax.swing.JComboBox<String> comboBoxGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner spinnerAge;
    private javax.swing.JTextArea textExperience;
    private javax.swing.JTextField textFirstName;
    private javax.swing.JTextField textLastName;
    private javax.swing.JFormattedTextField textPhoneNumber;
    private javax.swing.JLabel txtFilePath;
    private javax.swing.JTextArea txtHobbies;
    private javax.swing.JFormattedTextField txtemail;
    // End of variables declaration//GEN-END:variables
}
