/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lab4.ui;

import com.mycompany.lab4.model.User;
import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import com.mycompany.lab4.ui.ViewUserPanel;
import java.awt.Color;
import java.awt.GridBagLayout;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;


/**
 *
 * @author syedahmed
 */
public class MainJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainJFrame.class.getName());
    private CardLayout cardLayout;
    private JPanel mainCardPanel;
    private UserFormPanel userFormPanel;
    private ViewUserPanel viewUserDetailsPanel;
    private JScrollPane scrollPane = null;


    public ViewUserPanel getViewUserPanel(){
        return this.viewUserDetailsPanel;
    }
    /**
     * Creates new form UserForm
     */
    public MainJFrame() {
        initComponents();
        setupCardLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 581, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 603, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void setupCardLayout(){
        cardLayout = new CardLayout();
        mainCardPanel = new JPanel(cardLayout);
        scrollPane = new JScrollPane(mainCardPanel);

        userFormPanel = new UserFormPanel();
        viewUserDetailsPanel = new ViewUserPanel();
        
        mainCardPanel.add(userFormPanel,"User Form Panel");
        mainCardPanel.add(viewUserDetailsPanel,"view user details Panel");
        
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        
        // --- NEW CODE START ---
        
        // 1. Create the new top panel and make it green
        JPanel topGreenPanel = new JPanel();
        topGreenPanel.setBackground(java.awt.Color.GREEN);
        
        JLabel myLabel = new JLabel("User Registration Form");
        myLabel.setFont(myLabel.getFont().deriveFont(java.awt.Font.BOLD));
        topGreenPanel.add(myLabel); // Optional placeholder text
        
        // Enforce minimum sizes so the split divider behaves correctly
        topGreenPanel.setMaximumSize(new java.awt.Dimension(100, 50));
        scrollPane.setMinimumSize(new java.awt.Dimension(100, 100));
        
        // 2. Create the vertical split pane
        // Top: topGreenPanel, Bottom: scrollPane
        JSplitPane mainSplitPane = new JSplitPane(JSplitPane.VERTICAL_SPLIT, topGreenPanel, scrollPane);
        
        // 3. Configure the split pane properties
        mainSplitPane.setDividerLocation(50);      // Initial height of the green top panel in pixels
        mainSplitPane.setResizeWeight(0.0);         // The bottom (scrollPane) gets all the extra space when resizing
        mainSplitPane.setOneTouchExpandable(false);  // Adds quick collapse/expand arrows
        
        // --- NEW CODE END ---
    
        this.getContentPane().setLayout(new java.awt.BorderLayout());
        
        // 4. CHANGE THIS LINE: Add the splitPane to the frame instead of just the scrollPane
        this.getContentPane().add(mainSplitPane, java.awt.BorderLayout.CENTER);
        
        cardLayout.show(mainCardPanel,"User Form Panel");
        
    }
    
     public void switchCard(String cardName) {
        scrollPane.getVerticalScrollBar().setValue(0);
        cardLayout.show(mainCardPanel, cardName);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            
        
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        MainJFrame mainFrame = new MainJFrame();
        mainFrame.setLocationRelativeTo(null); 
        mainFrame.setVisible(true);
//        java.awt.EventQueue.invokeLater(() -> new MainJFrame().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
