/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.lab4.ui;

import com.mycompany.lab4.model.User;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.ImageIcon;

/**
 *
 * @author syedahmed
 */
public class ViewUserPanel extends javax.swing.JPanel {

    
    
    public void setUserData(User user){        
        
        txtAge.setText(String.valueOf(user.getAge()));
        txtContinent.setText(user.getContinent());
        txtEmail.setText(user.getEmail());
        txtExperience.setText(user.getExperience());
        txtFirstName.setText(user.getFirstName());
        txtGender.setText(user.getGender());
        txtHobbies.setText(user.getHobbies());
        txtLastName.setText(user.getLastName());
        txtPhoneNumber.setText(user.getPhoneNumber());
        txtdob.setText(convertDate(user.getDob()));
        
        
        imgView.setIcon(new ImageIcon(user.getPhotoUrl()));
        
        
        
    }
    
    /**
     * Creates new form ViewUserPanel
     */
    public ViewUserPanel() {
        initComponents();
           
    }
    

    
    private String convertDate(long timeStamp){
        Instant instant = Instant.ofEpochMilli(timeStamp);

        // 2. Convert to local date and time using system time zone
        
        LocalDate date = LocalDate.ofInstant(instant, ZoneId.systemDefault());
        
        
        return date.toString();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFirstName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JLabel();
        txtGender = new javax.swing.JLabel();
        txtAge = new javax.swing.JLabel();
        txtdob = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JLabel();
        txtEmail = new javax.swing.JLabel();
        txtContinent = new javax.swing.JLabel();
        txtExperience = new javax.swing.JLabel();
        txtHobbies = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtAge1 = new javax.swing.JLabel();
        txtdob1 = new javax.swing.JLabel();
        txtPhoneNumber1 = new javax.swing.JLabel();
        txtEmail1 = new javax.swing.JLabel();
        txtContinent1 = new javax.swing.JLabel();
        txtExperience1 = new javax.swing.JLabel();
        txtHobbies1 = new javax.swing.JLabel();
        txtFirstName1 = new javax.swing.JLabel();
        txtLastName1 = new javax.swing.JLabel();
        txtGender1 = new javax.swing.JLabel();
        imgView = new javax.swing.JLabel();

        txtFirstName.setText("First Name");

        txtLastName.setText("Last Name");

        txtGender.setText("Gender");

        txtAge.setText("Age");

        txtdob.setText("Date of Birth");

        txtPhoneNumber.setText("Phone Number");

        txtEmail.setText("Email");

        txtContinent.setText("Continent");

        txtExperience.setText("Experience");

        txtHobbies.setText("Hobbies");

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        txtAge1.setText("Age");

        txtdob1.setText("Date of Birth");

        txtPhoneNumber1.setText("Phone Number");

        txtEmail1.setText("Email");

        txtContinent1.setText("Continent");

        txtExperience1.setText("Experience");

        txtHobbies1.setText("Hobbies");

        txtFirstName1.setText("First Name");

        txtLastName1.setText("Last Name");

        txtGender1.setText("Gender");

        imgView.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHobbies1)
                            .addComponent(txtPhoneNumber1)
                            .addComponent(txtEmail1)
                            .addComponent(txtContinent1)
                            .addComponent(txtExperience1)
                            .addComponent(txtAge1)
                            .addComponent(txtFirstName1)
                            .addComponent(txtLastName1)
                            .addComponent(txtGender1)
                            .addComponent(txtdob1))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHobbies)
                            .addComponent(txtPhoneNumber)
                            .addComponent(txtEmail)
                            .addComponent(txtContinent)
                            .addComponent(txtExperience)
                            .addComponent(txtAge)
                            .addComponent(txtFirstName)
                            .addComponent(txtLastName)
                            .addComponent(txtGender)
                            .addComponent(txtdob)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imgView, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)))
                .addContainerGap(264, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFirstName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLastName)
                        .addGap(18, 18, 18)
                        .addComponent(txtGender)
                        .addGap(20, 20, 20)
                        .addComponent(txtAge)
                        .addGap(18, 18, 18)
                        .addComponent(txtdob)
                        .addGap(24, 24, 24)
                        .addComponent(txtPhoneNumber)
                        .addGap(18, 18, 18)
                        .addComponent(txtEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtContinent)
                        .addGap(18, 18, 18)
                        .addComponent(txtExperience)
                        .addGap(27, 27, 27)
                        .addComponent(txtHobbies))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFirstName1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLastName1)
                        .addGap(18, 18, 18)
                        .addComponent(txtGender1)
                        .addGap(20, 20, 20)
                        .addComponent(txtAge1)
                        .addGap(18, 18, 18)
                        .addComponent(txtdob1)
                        .addGap(24, 24, 24)
                        .addComponent(txtPhoneNumber1)
                        .addGap(18, 18, 18)
                        .addComponent(txtEmail1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtContinent1)
                        .addGap(18, 18, 18)
                        .addComponent(txtExperience1)
                        .addGap(27, 27, 27)
                        .addComponent(txtHobbies1)))
                .addGap(43, 43, 43)
                .addComponent(imgView, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(btnBack)
                .addContainerGap(155, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        
        MainJFrame mainFrame = (MainJFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        
        if (mainFrame != null) {
            mainFrame.switchCard("User Form Panel"); 
        }
        
    }//GEN-LAST:event_btnBackActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel imgView;
    private javax.swing.JLabel txtAge;
    private javax.swing.JLabel txtAge1;
    private javax.swing.JLabel txtContinent;
    private javax.swing.JLabel txtContinent1;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtEmail1;
    private javax.swing.JLabel txtExperience;
    private javax.swing.JLabel txtExperience1;
    private javax.swing.JLabel txtFirstName;
    private javax.swing.JLabel txtFirstName1;
    private javax.swing.JLabel txtGender;
    private javax.swing.JLabel txtGender1;
    private javax.swing.JLabel txtHobbies;
    private javax.swing.JLabel txtHobbies1;
    private javax.swing.JLabel txtLastName;
    private javax.swing.JLabel txtLastName1;
    private javax.swing.JLabel txtPhoneNumber;
    private javax.swing.JLabel txtPhoneNumber1;
    private javax.swing.JLabel txtdob;
    private javax.swing.JLabel txtdob1;
    // End of variables declaration//GEN-END:variables
}
